### ISSUE TITLE
maven install fails on goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign

### ISSUE THREAD

**Issue by ghost** [rtfarte/OpenPDF#12]
I get the following build failure error messages when running 'mvn install' on the current git master branch of this project, related to the goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign.

I think we should update the README to document how to build OpenPDF with maven-gpg-plugin.
 A workaround to fix 'mvn install' is to comment out the <plugin> containing the 'maven-gpg-plugin' in pom.xml.

> [INFO] ------------------------------------------------------------------------
> [INFO] Building OpenPDF - Free and Open PDF 1.0.0-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-javadoc-plugin:2.10.1:jar (attach-javadocs) @ openpdf-parent ---
> [INFO] Not executing Javadoc as the project is not a Java classpath-capable package
> [INFO]
> [INFO] --- maven-source-plugin:2.4:jar-no-fork (attach-sources) @ openpdf-parent ---
> [INFO]
> [INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ openpdf-parent ---
> gpg: no default secret key: secret key not available
> gpg: signing failed: secret key not available
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] OpenPDF - Free and Open PDF ........................ FAILURE [  1.450 s]
> [INFO] openpdf ............................................ SKIPPED
> [INFO] pdf-xml ............................................ SKIPPED
> [INFO] pdf-rtf ............................................ SKIPPED
> [INFO] pdf-html ........................................... SKIPPED
> [INFO] pdf-swing .......................................... SKIPPED
> [INFO] pdf-toolbox ........................................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1.635 s
> [INFO] Finished at: 2016-05-12T14:27:45+02:00
> [INFO] Final Memory: 14M/245M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project openpdf-parent: Exit code: 2 -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by syakovyn** [comment]
There is a simpler workaround: mvn install -Dgpg.skip=true

**Comment by ghost** [comment]
Thanks!  (Is there anything we can change in the pom.xml, so that 'mvn install' works out-of-the-box?)

**Comment by syakovyn** [comment]
https://github.com/rtfarte/OpenPDF/pull/13
