### ISSUE TITLE
License status?

### ISSUE THREAD

**Issue by jokimaki** [rtfarte/OpenPDF#17]
I noticed that you changed the license to MIT in b7af3578d56f80c322861c565e15cbe07201b229. However, the original iText source files state that they are licensed under LGPL/MPL. I assume that only new contributions are licensed under the MIT license? I don't think you can change the license of the whole code base unless you're the original copyright holder, especially from a restrictive license like LGPL to more permissive MIT.

Another question is what would be the license of the whole library. I'm under the impression that because LGPL is a copyleft license, the whole work would have to be licensed under that?

Perhaps you could clarify the license status in README? In my opinion the clearest and (from a legal perspective) safest thing to do would be to revert back to the original license. But again, I'm not a legal expert on FOSS licenses and I would just like to know your reasoning.

**Comment by ghost** [comment]
The license change was done by @rtfarte. Perhaps he can explain?

**Comment by jokimaki** [comment]
Don't get me wrong, I think it would be great to have as open license as possible :) But based on my understanding, changing the license of the whole project would mean we'd have to rewrite iText parts from scratch first, as stated in #6.

**Comment by ghost** [comment]
If we don't hear from @rtfarte about this, then I would gladly approve a pull-request to revert the license change.

**Comment by ghost** [comment]
Cannot comment other commits, but as you forked from my original code - I do not agree with license change, because it is illegal. Althought I aprreciate the work you are doing, I cannot simply agree with illegal activities. So please change it back to LGPL/MPL. Maybe for simplification (i do not like dual licenses) it will be preferable to use LGPL, but it depends on you.

**Comment by jokimaki** [comment]
Thanks for stating your case @kulatamicuda. I'll prepare a PR.

**Comment by ghost** [comment]
Now it's all good?

**Comment by bengolder** [comment]
Thanks everyone for noticing and handling this issue appropriately. I'll go ahead and pull these changes into the version published on Maven Central.

**Comment by gilbertoca** [comment]
@bengolder @rtfarte @kulatamicuda 
What about putting it in your own project? 
Like:
https://github.com/OpenPDF
https://github.com/OpenPDF/openpdf
https://github.com/OpenPDF/openpdf.github.io

**Comment by rtfarte** [comment]
Agreed. I just hated the licensing of the original project. I'm no lawyer, but to be safe we should revert back to the original license.

Thanks,
--Art

**Comment by lapo-luchini** [comment]
As a side issue: the license file currently contains text from MPL 2.0 / LGPL 2.1, but the readme talks about MPL 2.0 / LGPL 3.0.

I guess the license file is probably right, but then the readme should be corrected to LGPL 2.1 for clarity's sake.

**Comment by ghost** [comment]
See notes in files from original itext 4.2.0 on which this whole project is originally based:
* This library is free software; you can redistribute it and/or modify it
 * under the terms of the MPL as stated above or under the terms of the GNU
 * Library General Public License as published by the Free Software Foundation;
 * either version 2 of the License, **or any later version**.

**Comment by lapo-luchini** [comment]
Sure you can decide to upgrade the project from using LGPL 2.1+ to requiring LGPL 3.0+… but having one in the license file and another in the readme file doesn't makes much sense to me: should the user follow the 2.1 as _extensively_ stated in the license file or the 3.0 as _succinctly_ stated in the readme file?
(Myself, as a user, I'd prefer to keep using the 2.1, but that's not me to decide.)
With my comment I wasn't trying to advocate for one license or the other, just to have avoid clashing infos about it. :)
