### ISSUE TITLE
make an OpenPDF organization?

### ISSUE THREAD

**Issue by bengolder** [rtfarte/OpenPDF#19]
[This comment](https://github.com/rtfarte/OpenPDF/issues/17#issuecomment-255545135) by @gilbertoca suggests that we make an official repo under a github organization. I think that's a good idea. And it would make more sense to publish to Maven Central from an OpenPDF organization repo than from [the fork on my personal account](https://github.com/bengolder/openpdf).

What do you think?

**Comment by ghost** [comment]
Yes!

**Comment by bengolder** [comment]
Great, I'll try to set that up today or tomorrow, as well as pull in the license corrections. I'll close this issue when it's done.

**Comment by ghost** [comment]
By the way, does the name OpenPDF infringe on any PDF trademarks?

**Comment by ghost** [comment]
I have found this project https://sourceforge.net/projects/openpdf/

**Comment by bengolder** [comment]
https://github.com/OpenPDF is taken. I contacted github support and learned that it _is_ currently in use but the activity is not public

We would have to use a different organization name. These are available:
- open-pdf (or Open-PDF)
- pdf-open (or PDF-Open)

**Comment by ghost** [comment]
Some suggestions: OpenPDF4J, libOpenPDF, LGPLPDF, OPDFNT (OpenPDFisNotiText), YaPDFLib (Yet another PDF Library), LibrePDF

**Comment by gilbertoca** [comment]
I'm toward OpenPDF4J and LibrePDF.

**Comment by bengolder** [comment]
https://github.com/LibrePDF

I've sent some invitations. If you didn't get an invite, but you'd like to help maintain the organization, please let me know.

If you did get an invite but you're not interested in joining the organization. That's okay too. :) Feel free to ignore it.

I migrated my fork of the project to the organization:
https://github.com/LibrePDF/OpenPDF

**Comment by gilbertoca** [comment]
@rtfarte @andreasrosdal @bengolder I didn't understand. You didn't change anything. I thought the library would be called librepdf-1.0.jar and the organization LibrePDF. 
LibrePDF-->librepdf
If the idea was keep the same name, then OpenPDF4J makes more sense, no?
OpenPDF4J-->openpdf
instead of 
LivrePDF-->openpdf
